### ISSUE TITLE
Define a common development box using Docker to provision

### ISSUE THREAD

**Issue by meganmckissack** [hackoregon/housing-17#3]

**Comment by wfriedland** [comment]
Right now there is a vagrant development box. The DevOps class is building a docker development box. That is fine, however work that requires a development box can not wait until this development is completed. The vagrant development box should be used until the docker replacement is ready.

**Comment by znmeb** [comment]
@wfriedland @JohnTasto I'm doing some of the Docker things, most notably, adding the PostGIS capabilities to the PostgreSQL image. So I'm gathering requirements from the projects.

Will you be needing PostGIS? Any other GIS *services*? As of Saturday, the plan was to build a desktop Docker environment with two containers - one running Django and the other PostgreSQL / PostGIS.

**Comment by JohnTasto** [comment]
I was just wondering that as well, because I'm working on the same thing! I'm currently working Dockerizing the backend branch of this repo so the team can get going. If you come up with something more robust or generalized, I'll be happy to throw my work away.

There are several PostGIS images up on Docker Hub.

**Comment by znmeb** [comment]
We are going with https://hub.docker.com/_/postgres/, 9.5.5 (Debian base). Go ahead and build your backend and we'll refactor it when we're ready to start automating things.

**Comment by JohnTasto** [comment]
#27
